spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: kafka:9093
    consumer:
      auto-offset-reset: earliest
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: '*'
      group-id: myGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: kafka:9093
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
server:
  port: 9200
