server:
  port: 9000
keycloak:
  url: keycloak:8080
  realm: ${KEYCLOAK_REALM}
  client:
    id: ${KEYCLOAK_CLIENT_ID}
    secret: ${KEYCLOAK_CLIENT_SECRET}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME}
    password: ${KEYCLOAK_ADMIN_PASSWORD}

jwt-secret-key: ${JWT_SECRET_KEY}
