server:
  port: 9000
keycloak:
  url: keycloak:8080
  realm: atticket
  client:
    id: atticket
    secret: ${KEYCLOAK_CLIENT_SECRET}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME}
    password: ${KEYCLOAK_ADMIN_PASSWORD}
