version: "3.9"
services:
  reverse-proxy:
    image: nginx:1.21
    container_name: at_ticket-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    # SSL 적용
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #      - ./ssl/api/fullchain.pem:/etc/letsencrypt/live/api.atticket.o-r.kr/fullchain.pem
      #      - ./ssl/api/privkey.pem:/etc/letsencrypt/live/api.atticket.o-r.kr/privkey.pem
      #      - ./ssl/keycloak/fullchain.pem:/etc/letsencrypt/live/keycloak.atticket.o-r.kr/fullchain.pem
      #      - ./ssl/keycloak/privkey.pem:/etc/letsencrypt/live/keycloak.atticket.o-r.kr/privkey.pem

      - /home/at_ticket_setting/ssl/api/fullchain.pem:/etc/letsencrypt/live/api.atticket.o-r.kr/fullchain.pem
      - /home/at_ticket_setting/ssl/api/privkey.pem:/etc/letsencrypt/live/api.atticket.o-r.kr/privkey.pem
      - /home/at_ticket_setting/ssl/keycloak/fullchain.pem:/etc/letsencrypt/live/keycloak.atticket.o-r.kr/fullchain.pem
      - /home/at_ticket_setting/ssl/keycloak/privkey.pem:/etc/letsencrypt/live/keycloak.atticket.o-r.kr/privkey.pem


  database:
    image: mysql:8.0.21
    container_name: mysql
    #DB시작 시 초기화 스크립트 실행
    volumes:
      - ./mysql-init-files/:/docker-entrypoint-initdb.d/
      - db_volume:/var/lib/mysql
    expose:
      - 3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      JVM_OPTS: -Xmx1g -Xms1g -XX:MaxPermSize=1024m
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://kafka:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092


  product:
    #DB가 실행되기 전까진 어플리케이션이 실행되지 않도록 설정
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./product/Dockerfile
    container_name: at_ticket-product
    expose:
      - 8000
    environment:
      - SPRING_PROFILES_ACTIVE=dev


  reservation:
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./reservation/Dockerfile
    container_name: at_ticket-reservation
    expose:
      - 8100
    environment:
      - SPRING_PROFILES_ACTIVE=dev


  payment:
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./payment/Dockerfile
    container_name: at_ticket-payment
    expose:
      - 8200
    environment:
      - SPRING_PROFILES_ACTIVE=dev


  kafka-app:
    build:
      context: .
      dockerfile: ./kafka/Dockerfile
    container_name: at_ticket-kafka-app
    ports:
      - "9200:9200"
    depends_on:
      database:
        condition: service_healthy
      keycloak:
        condition: service_started
      kafka:
        condition: service_started
      zookeeper:
        condition: service_started

    environment:
      - SPRING_PROFILES_ACTIVE=dev


  user:
    #DB가 실행되기 전까진 어플리케이션이 실행되지 않도록 설정
    depends_on:
      database:
        condition: service_healthy
      keycloak:
        condition: service_started
    build:
      context: .
      dockerfile: ./user/Dockerfile
    container_name: at_ticket-user
    expose:
      - 9000
    environment:
      - SPRING_PROFILES_ACTIVE=dev


  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    container_name: at_ticket-keycloak
    expose:
      - 8080
    command: start --features=preview
    environment:
      - KC_DB=mysql
      - KC_DB_USERNAME=${DB_USERNAME}
      - KC_DB_PASSWORD=${DB_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB_URL=${DB_KEYCLOAK_URL}
    volumes:
      - ./keycloak/dev.conf:/opt/keycloak/conf/keycloak.conf
    depends_on:
      database:
        condition: service_healthy
volumes:
  db_volume:
