version: "3.0"
services:
  database:
    image: mysql
    container_name: at_ticket_db
    #DB시작 시 초기화 스크립트 실행
    volumes:
      - ./mysql-init-files/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10


  product:
    #DB가 실행되기 전까진 어플리케이션이 실행되지 않도록 설정
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./product/Dockerfile
    container_name: at_ticket-product
    ports:
      - 8000:8000
    environment:
      - SPRING_PROFILES_ACTIVE=dev


  reservation:
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./reservation/Dockerfile
    container_name: at_ticket-reservation
    ports:
      - 8100:8100
    environment:
      - SPRING_PROFILES_ACTIVE=dev


  payment:
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./payment/Dockerfile
    container_name: at_ticket-payment
    ports:
      - 8200:8200
    environment:
      - SPRING_PROFILES_ACTIVE=dev


  user:
    #DB가 실행되기 전까진 어플리케이션이 실행되지 않도록 설정
    depends_on:
      database:
        condition: service_healthy
      keycloak:
        condition: service_started
    build:
      context: .
      dockerfile: ./user/Dockerfile
    container_name: at_ticket-user
    ports:
      - 9000:9000
    environment:
      - SPRING_PROFILES_ACTIVE=dev


  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    container_name: at_ticket-keycloak
    ports:
      - 8080:8080
    command: start-dev --features=preview
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=atticket
    volumes:
      - ./keycloak/local.conf:/opt/keycloak/conf/keycloak.conf
    depends_on:
      database:
        condition: service_healthy
