version: "3.0"
services:
  product:
    build:
      context: .
      dockerfile: ./product/Dockerfile
    container_name: "at_ticket-product"
    ports:
      - "8000:8000"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
  reservation:
    build:
      context: .
      dockerfile: ./reservation/Dockerfile
    container_name: "at_ticket-reservation"
    expose:
      - "8100"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
  payment:
    build:
      context: .
      dockerfile: ./payment/Dockerfile
    container_name: "at_ticket-payment"
    expose:
      - "8200"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
