CREATE
DATABASE IF NOT EXISTS product;
CREATE
DATABASE IF NOT EXISTS reservation;
CREATE
DATABASE IF NOT EXISTS payment;
CREATE
DATABASE IF NOT EXISTS keycloak;
CREATE
DATABASE IF NOT EXISTS user_info;
