server:
  port: 8100

api:
  product:
    url: product
    port: 8000
  payment:
    url: payment
    port: 8200

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://223.130.147.179/:3306/reservation?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

jwt-secret-key: ${JWT_SECRET_KEY}

# management:
#   endpoints:
#     web:
#       exposure:
#         include: prometheus
